In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import matplotlib.dates as mdates

import math

In [2]:
#加载时间
timelist = []
for i in range(12):
    timelist.append(str(201101 + i))
    
for i in range(12):
    timelist.append(str(201201 + i))
    
for i in range(12):
    timelist.append(str(201301 + i))

for i in range(12):
    timelist.append(str(201401 + i))
    
for i in range(12):
    timelist.append(str(201501 + i))
    
for i in range(12):
    timelist.append(str(201601 + i))

for i in range(12):
    timelist.append(str(201701 + i))
    
for i in range(12):
    timelist.append(str(201801 + i))

for i in range(12):
    timelist.append(str(201901 + i))
    
for i in range(12):
    timelist.append(str(202001 + i))
    
for i in range(5):
    timelist.append(str(202101 + i))

In [67]:
#将所有日期数据合并
ex_alldata = pd.DataFrame(columns=['rtTitle', 'ptTitle', 'TradeValue', 'monthdate'])
for i in timelist:
    ex_result = pd.read_csv(i + '_APEC_export_trade.csv')
    ex_result['monthdate'] = i
    ex_alldata=pd.concat([ex_alldata, ex_result])
    
#获取每个国家每个月出口总额
ex_alldata['TradeValue'] = pd.to_numeric(ex_alldata['TradeValue'], downcast='float')
ex_month_total = ex_alldata[ex_alldata['ptTitle'] == 'World']
ex_month_total['TradeValue'] = ex_month_total['TradeValue']/(10 ** 9)
#获取国家名code映射
counrty_code = pd.read_csv('nodes.csv')
code_book = pd.read_csv('codebook.csv', header=None, sep="	")
code_book.columns = ['0','country_code','Label','3','4','5','6','7']

#获取各个国家的code
ex_month_total.columns=['Id', 'ptTitle', 'TradeValue', 'monthdate']
ex_month_total_2 = pd.merge(counrty_code, ex_month_total, on='Id',how='right')
ex_month_total_id = pd.merge(code_book, ex_month_total_2, on='Label',how='inner')
ex_month_total_id['monthdate'] = pd.to_datetime(ex_month_total_id['monthdate'].astype('str'),format = '%Y%m')

C:\Users\yuwang\AppData\Local\Temp\ipykernel_8592\1309333907.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ex_month_total['TradeValue'] = ex_month_total['TradeValue']/(10 ** 9)

In [66]:
ex_alldata[(ex_alldata['ptTitle'] == 'World') & (ex_alldata['rtTitle'] == 'Viet Nam')]

       rtTitle ptTitle    TradeValue monthdate
3026  Viet Nam   World  1.340473e+10    201501
2921  Viet Nam   World  9.513173e+09    201502
2975  Viet Nam   World  1.334474e+10    201503
3035  Viet Nam   World  1.348955e+10    201504
3026  Viet Nam   World  1.364807e+10    201505
...        ...     ...           ...       ...
2751  Viet Nam   World  2.770247e+10    202008
2670  Viet Nam   World  2.716281e+10    202009
2763  Viet Nam   World  2.690719e+10    202010
2759  Viet Nam   World  2.488271e+10    202011
2652  Viet Nam   World  2.727274e+10    202012

[65 rows x 4 columns]

In [68]:
#保存结果
new_dataframe = ex_month_total_id['country_code'].unique()
new_dataframe.sort()
result_frame = ['month']
for i in new_dataframe:
    #去除塞尔维亚和黑山 SC
    if i == 'SC':
        continue
    result_frame.append(i)
result_pd = pd.DataFrame(columns = result_frame)
#将国家转化为列输出，空值为0
export_data = ex_month_total_id[['monthdate','country_code','TradeValue']]
for month in export_data['monthdate'].unique():
    fill_country_list = [month]
    for country in new_dataframe:
        #去除塞尔维亚和黑山 SC
        if country == 'SC':
            continue
        if(export_data[(export_data['monthdate'] == month) & (export_data['country_code'] == country)].empty == 0):
            fill_country_list.append(export_data[(export_data['monthdate'] == month) & (export_data['country_code'] == country)].iloc[0,2])
        else:
            fill_country_list.append(0)
    result_pd.loc[len(result_pd)] = fill_country_list

In [69]:
result_pd.to_csv('201101_202105_export.csv',index = False)

In [8]:
#数量统计
export_data = ex_month_total_id[['monthdate','Id','TradeValue']]
fill_country_list = []
#将空值补齐，并转化为nan
for country in ex_month_total_id['Id'].unique():
    for month in export_data['monthdate'].unique():
        if(export_data[(export_data['monthdate'] == month) & (export_data['Id'] == country)].empty == 1):
            print(month,country)
            #import_data.loc[len(import_data)] = [month,country,None]
#             fill_country_list.append(country)
#             print(month,country)
#             break

2012-08-01T00:00:00.000000000 Canada
2012-12-01T00:00:00.000000000 Canada
2013-10-01T00:00:00.000000000 Canada
2014-09-01T00:00:00.000000000 Canada
2016-08-01T00:00:00.000000000 Canada
2016-09-01T00:00:00.000000000 Canada
2016-10-01T00:00:00.000000000 Canada
2019-12-01T00:00:00.000000000 Canada
2020-01-01T00:00:00.000000000 Canada
2020-02-01T00:00:00.000000000 Canada
2012-08-01T00:00:00.000000000 Australia
2012-12-01T00:00:00.000000000 Australia
2013-10-01T00:00:00.000000000 Australia
2014-09-01T00:00:00.000000000 Australia
2016-08-01T00:00:00.000000000 Australia
2016-09-01T00:00:00.000000000 Australia
2016-10-01T00:00:00.000000000 Australia
2019-12-01T00:00:00.000000000 Australia
2020-01-01T00:00:00.000000000 Australia
2020-02-01T00:00:00.000000000 Australia
2012-08-01T00:00:00.000000000 Brunei Darussalam
2012-12-01T00:00:00.000000000 Brunei Darussalam
2013-10-01T00:00:00.000000000 Brunei Darussalam
2014-01-01T00:00:00.000000000 Brunei Darussalam
2014-02-01T00:00:00.000000000 Brunei Darussalam
2014-03-01T00:00:00.000000000 Brunei Darussalam
2014-04-01T00:00:00.000000000 Brunei Darussalam
2014-05-01T00:00:00.000000000 Brunei Darussalam
2014-06-01T00:00:00.000000000 Brunei Darussalam
2014-07-01T00:00:00.000000000 Brunei Darussalam
2014-08-01T00:00:00.000000000 Brunei Darussalam
2014-09-01T00:00:00.000000000 Brunei Darussalam
2014-10-01T00:00:00.000000000 Brunei Darussalam
2014-11-01T00:00:00.000000000 Brunei Darussalam
2014-12-01T00:00:00.000000000 Brunei Darussalam
2016-08-01T00:00:00.000000000 Brunei Darussalam
2016-09-01T00:00:00.000000000 Brunei Darussalam
2016-10-01T00:00:00.000000000 Brunei Darussalam
2019-12-01T00:00:00.000000000 Brunei Darussalam
2020-01-01T00:00:00.000000000 Brunei Darussalam
2020-02-01T00:00:00.000000000 Brunei Darussalam
2021-01-01T00:00:00.000000000 Brunei Darussalam
2021-02-01T00:00:00.000000000 Brunei Darussalam
2021-03-01T00:00:00.000000000 Brunei Darussalam
2021-04-01T00:00:00.000000000 Brunei Darussalam
2021-05-01T00:00:00.000000000 Brunei Darussalam
2011-12-01T00:00:00.000000000 China
2012-10-01T00:00:00.000000000 China
2012-11-01T00:00:00.000000000 China
2012-12-01T00:00:00.000000000 China
2013-01-01T00:00:00.000000000 China
2013-02-01T00:00:00.000000000 China
2013-03-01T00:00:00.000000000 China
2013-04-01T00:00:00.000000000 China
2013-05-01T00:00:00.000000000 China
2013-06-01T00:00:00.000000000 China
2013-07-01T00:00:00.000000000 China
2013-08-01T00:00:00.000000000 China
2013-09-01T00:00:00.000000000 China
2013-10-01T00:00:00.000000000 China
2013-11-01T00:00:00.000000000 China
2013-12-01T00:00:00.000000000 China
2014-01-01T00:00:00.000000000 China
2014-02-01T00:00:00.000000000 China
2014-03-01T00:00:00.000000000 China
2014-04-01T00:00:00.000000000 China
2014-05-01T00:00:00.000000000 China
2014-06-01T00:00:00.000000000 China
2014-07-01T00:00:00.000000000 China
2014-08-01T00:00:00.000000000 China
2014-09-01T00:00:00.000000000 China
2014-10-01T00:00:00.000000000 China
2014-11-01T00:00:00.000000000 China
2014-12-01T00:00:00.000000000 China
2015-01-01T00:00:00.000000000 China
2015-02-01T00:00:00.000000000 China
2015-03-01T00:00:00.000000000 China
2015-04-01T00:00:00.000000000 China
2015-05-01T00:00:00.000000000 China
2015-06-01T00:00:00.000000000 China
2015-07-01T00:00:00.000000000 China
2015-08-01T00:00:00.000000000 China
2015-09-01T00:00:00.000000000 China
2015-10-01T00:00:00.000000000 China
2015-11-01T00:00:00.000000000 China
2015-12-01T00:00:00.000000000 China
2016-11-01T00:00:00.000000000 China
2020-01-01T00:00:00.000000000 China
2011-12-01T00:00:00.000000000 Chile
2014-02-01T00:00:00.000000000 Chile
2014-03-01T00:00:00.000000000 Chile
2014-07-01T00:00:00.000000000 Chile
2014-09-01T00:00:00.000000000 Chile
2015-08-01T00:00:00.000000000 Chile
2016-11-01T00:00:00.000000000 Chile
2020-01-01T00:00:00.000000000 Chile
2011-12-01T00:00:00.000000000 China, Hong Kong SAR
2014-02-01T00:00:00.000000000 China, Hong Kong SAR
2014-03-01T00:00:00.000000000 China, Hong Kong SAR
2014-07-01T00:00:00.000000000 China, Hong Kong SAR
2014-09-01T00:00:00.000000000 China, Hong Kong SAR
2015-08-01T00:00:00.000000000 China, Hong Kong SAR
2016-11-01T00:00:00.000000000 China, Hong Kong SAR
2020-01-01T00:00:00.000000000 China, Hong Kong SAR
2011-06-01T00:00:00.000000000 Japan
2012-08-01T00:00:00.000000000 Japan
2013-05-01T00:00:00.000000000 Japan
2013-06-01T00:00:00.000000000 Japan
2014-02-01T00:00:00.000000000 Japan
2016-08-01T00:00:00.000000000 Japan
2016-09-01T00:00:00.000000000 Japan
2020-02-01T00:00:00.000000000 Japan
2011-06-01T00:00:00.000000000 Malaysia
2012-08-01T00:00:00.000000000 Malaysia
2013-05-01T00:00:00.000000000 Malaysia
2013-06-01T00:00:00.000000000 Malaysia
2014-02-01T00:00:00.000000000 Malaysia
2014-07-01T00:00:00.000000000 Malaysia
2016-08-01T00:00:00.000000000 Malaysia
2016-09-01T00:00:00.000000000 Malaysia
2020-02-01T00:00:00.000000000 Malaysia
2011-06-01T00:00:00.000000000 Mexico
2012-02-01T00:00:00.000000000 Mexico
2013-01-01T00:00:00.000000000 Mexico
2013-05-01T00:00:00.000000000 Mexico
2014-02-01T00:00:00.000000000 Mexico
2014-07-01T00:00:00.000000000 Mexico
2015-10-01T00:00:00.000000000 Mexico
2016-01-01T00:00:00.000000000 Mexico
2018-12-01T00:00:00.000000000 Mexico
2020-02-01T00:00:00.000000000 Mexico
2020-03-01T00:00:00.000000000 Mexico
2020-04-01T00:00:00.000000000 Mexico
2011-06-01T00:00:00.000000000 New Zealand
2012-02-01T00:00:00.000000000 New Zealand
2013-01-01T00:00:00.000000000 New Zealand
2013-05-01T00:00:00.000000000 New Zealand
2014-02-01T00:00:00.000000000 New Zealand
2014-07-01T00:00:00.000000000 New Zealand
2015-10-01T00:00:00.000000000 New Zealand
2016-01-01T00:00:00.000000000 New Zealand
2018-12-01T00:00:00.000000000 New Zealand
2020-02-01T00:00:00.000000000 New Zealand
2020-03-01T00:00:00.000000000 New Zealand
2020-04-01T00:00:00.000000000 New Zealand
2012-12-01T00:00:00.000000000 United States of America
2013-01-01T00:00:00.000000000 United States of America
2013-06-01T00:00:00.000000000 United States of America
2013-11-01T00:00:00.000000000 United States of America
2014-01-01T00:00:00.000000000 United States of America
2014-02-01T00:00:00.000000000 United States of America
2014-04-01T00:00:00.000000000 United States of America
2015-10-01T00:00:00.000000000 United States of America
2016-11-01T00:00:00.000000000 United States of America
2017-01-01T00:00:00.000000000 United States of America
2018-08-01T00:00:00.000000000 United States of America
2020-01-01T00:00:00.000000000 United States of America
2020-02-01T00:00:00.000000000 United States of America
2020-04-01T00:00:00.000000000 United States of America
2011-01-01T00:00:00.000000000 Peru
2011-05-01T00:00:00.000000000 Peru
2014-02-01T00:00:00.000000000 Peru
2015-08-01T00:00:00.000000000 Peru
2015-09-01T00:00:00.000000000 Peru
2015-10-01T00:00:00.000000000 Peru
2016-09-01T00:00:00.000000000 Peru
2020-02-01T00:00:00.000000000 Peru
2020-03-01T00:00:00.000000000 Peru
2020-04-01T00:00:00.000000000 Peru
2020-05-01T00:00:00.000000000 Peru
2020-06-01T00:00:00.000000000 Peru
2020-07-01T00:00:00.000000000 Peru
2020-08-01T00:00:00.000000000 Peru
2020-09-01T00:00:00.000000000 Peru
2020-10-01T00:00:00.000000000 Peru
2020-11-01T00:00:00.000000000 Peru
2020-12-01T00:00:00.000000000 Peru
2021-01-01T00:00:00.000000000 Peru
2021-02-01T00:00:00.000000000 Peru
2021-03-01T00:00:00.000000000 Peru
2021-04-01T00:00:00.000000000 Peru
2021-05-01T00:00:00.000000000 Peru
2011-01-01T00:00:00.000000000 Philippines
2011-05-01T00:00:00.000000000 Philippines
2014-02-01T00:00:00.000000000 Philippines
2015-08-01T00:00:00.000000000 Philippines
2015-09-01T00:00:00.000000000 Philippines
2015-10-01T00:00:00.000000000 Philippines
2016-09-01T00:00:00.000000000 Philippines
2019-06-01T00:00:00.000000000 Philippines
2020-02-01T00:00:00.000000000 Philippines
2020-03-01T00:00:00.000000000 Philippines
2020-04-01T00:00:00.000000000 Philippines
2011-01-01T00:00:00.000000000 Thailand
2012-11-01T00:00:00.000000000 Thailand
2012-12-01T00:00:00.000000000 Thailand
2015-10-01T00:00:00.000000000 Thailand
2019-03-01T00:00:00.000000000 Thailand
2019-10-01T00:00:00.000000000 Thailand
2020-03-01T00:00:00.000000000 Thailand
2021-01-01T00:00:00.000000000 Thailand
2021-02-01T00:00:00.000000000 Thailand
2021-03-01T00:00:00.000000000 Thailand
2021-04-01T00:00:00.000000000 Thailand
2021-05-01T00:00:00.000000000 Thailand
2011-01-01T00:00:00.000000000 Singapore
2012-11-01T00:00:00.000000000 Singapore
2012-12-01T00:00:00.000000000 Singapore
2015-10-01T00:00:00.000000000 Singapore
2019-03-01T00:00:00.000000000 Singapore
2020-03-01T00:00:00.000000000 Singapore
2011-01-01T00:00:00.000000000 Indonesia
2011-02-01T00:00:00.000000000 Indonesia
2011-03-01T00:00:00.000000000 Indonesia
2011-04-01T00:00:00.000000000 Indonesia
2011-05-01T00:00:00.000000000 Indonesia
2011-06-01T00:00:00.000000000 Indonesia
2011-07-01T00:00:00.000000000 Indonesia
2011-08-01T00:00:00.000000000 Indonesia
2011-09-01T00:00:00.000000000 Indonesia
2011-10-01T00:00:00.000000000 Indonesia
2011-11-01T00:00:00.000000000 Indonesia
2011-12-01T00:00:00.000000000 Indonesia
2012-01-01T00:00:00.000000000 Indonesia
2012-02-01T00:00:00.000000000 Indonesia
2012-03-01T00:00:00.000000000 Indonesia
2012-04-01T00:00:00.000000000 Indonesia
2012-05-01T00:00:00.000000000 Indonesia
2012-06-01T00:00:00.000000000 Indonesia
2012-07-01T00:00:00.000000000 Indonesia
2012-08-01T00:00:00.000000000 Indonesia
2012-09-01T00:00:00.000000000 Indonesia
2012-10-01T00:00:00.000000000 Indonesia
2012-11-01T00:00:00.000000000 Indonesia
2013-05-01T00:00:00.000000000 Indonesia
2013-06-01T00:00:00.000000000 Indonesia
2013-09-01T00:00:00.000000000 Indonesia
2014-02-01T00:00:00.000000000 Indonesia
2014-11-01T00:00:00.000000000 Indonesia
2014-12-01T00:00:00.000000000 Indonesia
2016-08-01T00:00:00.000000000 Indonesia
2016-09-01T00:00:00.000000000 Indonesia
2020-02-01T00:00:00.000000000 Indonesia
2011-01-01T00:00:00.000000000 Rep. of Korea
2011-02-01T00:00:00.000000000 Rep. of Korea
2011-03-01T00:00:00.000000000 Rep. of Korea
2011-04-01T00:00:00.000000000 Rep. of Korea
2011-05-01T00:00:00.000000000 Rep. of Korea
2011-06-01T00:00:00.000000000 Rep. of Korea
2011-07-01T00:00:00.000000000 Rep. of Korea
2011-08-01T00:00:00.000000000 Rep. of Korea
2011-09-01T00:00:00.000000000 Rep. of Korea
2011-10-01T00:00:00.000000000 Rep. of Korea
2011-11-01T00:00:00.000000000 Rep. of Korea
2011-12-01T00:00:00.000000000 Rep. of Korea
2012-01-01T00:00:00.000000000 Rep. of Korea
2012-02-01T00:00:00.000000000 Rep. of Korea
2012-03-01T00:00:00.000000000 Rep. of Korea
2012-04-01T00:00:00.000000000 Rep. of Korea
2012-05-01T00:00:00.000000000 Rep. of Korea
2012-06-01T00:00:00.000000000 Rep. of Korea
2012-07-01T00:00:00.000000000 Rep. of Korea
2012-08-01T00:00:00.000000000 Rep. of Korea
2012-09-01T00:00:00.000000000 Rep. of Korea
2012-10-01T00:00:00.000000000 Rep. of Korea
2012-11-01T00:00:00.000000000 Rep. of Korea
2012-12-01T00:00:00.000000000 Rep. of Korea
2014-02-01T00:00:00.000000000 Rep. of Korea
2015-08-01T00:00:00.000000000 Rep. of Korea
2015-09-01T00:00:00.000000000 Rep. of Korea
2015-10-01T00:00:00.000000000 Rep. of Korea
2016-09-01T00:00:00.000000000 Rep. of Korea
2020-01-01T00:00:00.000000000 Rep. of Korea
2020-02-01T00:00:00.000000000 Rep. of Korea
2020-03-01T00:00:00.000000000 Rep. of Korea
2020-04-01T00:00:00.000000000 Rep. of Korea
2020-05-01T00:00:00.000000000 Rep. of Korea
2020-06-01T00:00:00.000000000 Rep. of Korea
2020-07-01T00:00:00.000000000 Rep. of Korea
2020-08-01T00:00:00.000000000 Rep. of Korea
2020-09-01T00:00:00.000000000 Rep. of Korea
2020-10-01T00:00:00.000000000 Rep. of Korea
2020-11-01T00:00:00.000000000 Rep. of Korea
2020-12-01T00:00:00.000000000 Rep. of Korea
2021-01-01T00:00:00.000000000 Rep. of Korea
2021-02-01T00:00:00.000000000 Rep. of Korea
2021-03-01T00:00:00.000000000 Rep. of Korea

2021-04-01T00:00:00.000000000 Rep. of Korea
2021-05-01T00:00:00.000000000 Rep. of Korea
2011-01-01T00:00:00.000000000 Russian Federation
2011-02-01T00:00:00.000000000 Russian Federation
2011-03-01T00:00:00.000000000 Russian Federation
2011-04-01T00:00:00.000000000 Russian Federation
2011-05-01T00:00:00.000000000 Russian Federation
2011-06-01T00:00:00.000000000 Russian Federation
2011-07-01T00:00:00.000000000 Russian Federation
2011-08-01T00:00:00.000000000 Russian Federation
2011-09-01T00:00:00.000000000 Russian Federation
2011-10-01T00:00:00.000000000 Russian Federation
2011-11-01T00:00:00.000000000 Russian Federation
2011-12-01T00:00:00.000000000 Russian Federation
2012-01-01T00:00:00.000000000 Russian Federation
2012-02-01T00:00:00.000000000 Russian Federation
2012-03-01T00:00:00.000000000 Russian Federation
2012-04-01T00:00:00.000000000 Russian Federation
2012-05-01T00:00:00.000000000 Russian Federation
2012-06-01T00:00:00.000000000 Russian Federation
2012-07-01T00:00:00.000000000 Russian Federation
2012-08-01T00:00:00.000000000 Russian Federation
2012-09-01T00:00:00.000000000 Russian Federation
2012-10-01T00:00:00.000000000 Russian Federation
2012-11-01T00:00:00.000000000 Russian Federation
2012-12-01T00:00:00.000000000 Russian Federation
2015-10-01T00:00:00.000000000 Russian Federation
2019-03-01T00:00:00.000000000 Russian Federation
2020-01-01T00:00:00.000000000 Russian Federation
2020-02-01T00:00:00.000000000 Russian Federation
2020-03-01T00:00:00.000000000 Russian Federation
2020-04-01T00:00:00.000000000 Russian Federation
2020-05-01T00:00:00.000000000 Russian Federation
2020-06-01T00:00:00.000000000 Russian Federation
2020-07-01T00:00:00.000000000 Russian Federation
2020-08-01T00:00:00.000000000 Russian Federation
2020-09-01T00:00:00.000000000 Russian Federation
2020-10-01T00:00:00.000000000 Russian Federation
2020-11-01T00:00:00.000000000 Russian Federation
2020-12-01T00:00:00.000000000 Russian Federation
2021-01-01T00:00:00.000000000 Russian Federation
2021-02-01T00:00:00.000000000 Russian Federation
2021-03-01T00:00:00.000000000 Russian Federation
2021-04-01T00:00:00.000000000 Russian Federation
2021-05-01T00:00:00.000000000 Russian Federation
2011-01-01T00:00:00.000000000 Viet Nam
2011-02-01T00:00:00.000000000 Viet Nam
2011-03-01T00:00:00.000000000 Viet Nam
2011-04-01T00:00:00.000000000 Viet Nam
2011-05-01T00:00:00.000000000 Viet Nam
2011-06-01T00:00:00.000000000 Viet Nam
2011-07-01T00:00:00.000000000 Viet Nam
2011-08-01T00:00:00.000000000 Viet Nam
2011-09-01T00:00:00.000000000 Viet Nam
2011-10-01T00:00:00.000000000 Viet Nam
2011-11-01T00:00:00.000000000 Viet Nam
2011-12-01T00:00:00.000000000 Viet Nam
2012-01-01T00:00:00.000000000 Viet Nam
2012-02-01T00:00:00.000000000 Viet Nam
2012-03-01T00:00:00.000000000 Viet Nam
2012-04-01T00:00:00.000000000 Viet Nam
2012-05-01T00:00:00.000000000 Viet Nam
2012-06-01T00:00:00.000000000 Viet Nam
2012-07-01T00:00:00.000000000 Viet Nam
2012-08-01T00:00:00.000000000 Viet Nam
2012-09-01T00:00:00.000000000 Viet Nam
2012-10-01T00:00:00.000000000 Viet Nam
2012-11-01T00:00:00.000000000 Viet Nam
2012-12-01T00:00:00.000000000 Viet Nam
2013-01-01T00:00:00.000000000 Viet Nam
2013-02-01T00:00:00.000000000 Viet Nam
2013-03-01T00:00:00.000000000 Viet Nam
2013-04-01T00:00:00.000000000 Viet Nam
2013-05-01T00:00:00.000000000 Viet Nam
2013-06-01T00:00:00.000000000 Viet Nam
2013-07-01T00:00:00.000000000 Viet Nam
2013-08-01T00:00:00.000000000 Viet Nam
2013-09-01T00:00:00.000000000 Viet Nam
2013-10-01T00:00:00.000000000 Viet Nam
2013-11-01T00:00:00.000000000 Viet Nam
2013-12-01T00:00:00.000000000 Viet Nam
2014-01-01T00:00:00.000000000 Viet Nam
2014-02-01T00:00:00.000000000 Viet Nam
2014-03-01T00:00:00.000000000 Viet Nam
2014-04-01T00:00:00.000000000 Viet Nam
2014-05-01T00:00:00.000000000 Viet Nam
2014-06-01T00:00:00.000000000 Viet Nam
2014-07-01T00:00:00.000000000 Viet Nam
2014-08-01T00:00:00.000000000 Viet Nam
2014-09-01T00:00:00.000000000 Viet Nam
2014-10-01T00:00:00.000000000 Viet Nam
2014-11-01T00:00:00.000000000 Viet Nam
2014-12-01T00:00:00.000000000 Viet Nam
2015-10-01T00:00:00.000000000 Viet Nam
2016-11-01T00:00:00.000000000 Viet Nam
2017-01-01T00:00:00.000000000 Viet Nam
2018-08-01T00:00:00.000000000 Viet Nam
2020-01-01T00:00:00.000000000 Viet Nam
2020-02-01T00:00:00.000000000 Viet Nam
2020-04-01T00:00:00.000000000 Viet Nam
2021-01-01T00:00:00.000000000 Viet Nam
2021-02-01T00:00:00.000000000 Viet Nam
2021-03-01T00:00:00.000000000 Viet Nam
2021-04-01T00:00:00.000000000 Viet Nam
2021-05-01T00:00:00.000000000 Viet Nam

In [70]:
pd.set_option('display.max_rows', 20)
pd.set_option('display.max_columns', 20)
result_pd

,month,AS,BX,CA,CH,CI,HK,ID,JA,KS,MX,MY,NZ,PE,RP,RS,SN,TH,US,VM
0,2011-01-01,17.313724,0.893574,34.150240,150.734143,6.519719,37.079556,0.000000,60.165272,0.000000,24.672324,17.914313,2.520392,0.000000,0.000000,0.000000,0.000000,0.000000,110.200816,0.000000
1,2011-02-01,17.417789,0.886478,32.710715,96.736125,6.040973,29.499402,0.000000,67.749880,0.000000,25.768737,17.007213,2.950242,3.379350,3.864879,0.000000,36.168278,18.356238,109.745136,0.000000
2,2011-03-01,21.766550,1.045558,39.623963,152.199070,7.751879,36.703568,0.000000,71.659479,0.000000,31.346174,21.093761,3.355219,3.751788,4.353293,0.000000,46.046663,20.878309,131.010675,0.000000
3,2011-04-01,21.823787,1.060656,36.180922,155.684078,7.294034,32.953203,0.000000,61.869126,0.000000,27.946338,19.183962,3.655071,3.417370,4.302154,0.000000,42.528711,17.256481,123.752792,0.000000
4,2011-05-01,24.154380,0.791102,38.029345,157.157196,7.421098,36.729803,0.000000,58.581516,0.000000,31.091399,18.284409,3.681868,0.000000,0.000000,0.000000,42.255602,18.998661,123.812684,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,2016-10-01,0.000000,0.000000,0.000000,176.870064,4.790821,44.774371,12.743736,56.543670,41.982411,32.589386,16.563401,2.783163,3.508333,4.938312,26.383143,28.654117,17.756856,128.473620,15.400691
121,2019-12-01,0.000000,0.000000,0.000000,238.604927,6.644037,48.285565,14.428818,60.245602,45.667869,38.727012,20.835293,3.650525,4.581119,5.750709,39.965635,33.200998,19.153701,135.752671,22.560793
122,2020-02-01,0.000000,0.000000,0.000000,80.372220,4.972012,31.643150,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,31.310586,20.641741,0.000000,0.000000
123,2014-09-01,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,15.275846,59.512963,50.357862,34.147312,20.050022,2.951123,3.308546,5.848901,38.395949,35.093848,19.912733,133.416952,0.000000
124,2020-01-01,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.636412,49.707983,0.000000,33.583714,20.660683,3.122687,3.700568,5.801894,0.000000,32.939534,19.625630,0.000000,0.000000