In [ ]:
#查询时间段所有媒体广告数量分布
select 
distinct
SourceCommonName,
count(*) as nums
from 
`dotted-marking-340807.test_20210101_202103031.wangyu_201906_202105_table` A
group by
SourceCommonName
order by nums desc

#47687个广告保存42,918

In [ ]:
#按照报道数量排序
select 
sum(case when nums=1  THEN 1 else 0 END) as n1,
sum(case when nums=2  THEN 1 else 0 END) as n2,
sum(case when nums=3  THEN 1 else 0 END) as n3,
sum(case when nums=4  THEN 1 else 0 END) as n4,
sum(case when nums=5  THEN 1 else 0 END) as n5,
sum(case when nums>=6 and nums<=10 THEN 1 else 0 END) as n6_10,
sum(case when nums>=11 and nums<=100 THEN 1 else 0 END) as n10_100,
sum(case when nums>=101 and nums<=1000 THEN 1 else 0 END) as n100_1000,
sum(case when nums>=1001 and nums<=10000 THEN 1 else 0 END) as n1000_1w,
sum(case when nums>=10001 THEN 1 else 0 END) as more_1w
from 
`dotted-marking-340807.test_20210101_202103031.source_count`

In [ ]:
#获取19年6月到21年5月，67个国家，90%媒体的数据
select 
D.*
from 
`dotted-marking-340807.test_20210101_202103031.67_country_code` A 
join `dotted-marking-340807.test_20210101_202103031.url_to_country` C 
on A.country_code = C.country_code
join `dotted-marking-340807.test_20210101_202103031.wangyu_201906_202105_table` D 
on C.url = D.SourceCommonName
join `dotted-marking-340807.test_20210101_202103031.wangyu_201906_202105_source_table` B 
on B.SourceCommonName = D.SourceCommonName

In [ ]:
#获取两年每个国家按日期的报道数和被报道数
SELECT
FLOOR(date/1000000) as yeardate,
B.country_code,
substring(V2Locations,instr(V2Locations,'#',1,2)+1,instr(V2Locations,'#',1,3)-instr(V2Locations,'#',1,2)-1) as report_code,
count(*) as report_nums
FROM `dotted-marking-340807.test_20210101_202103031.wangyu_201906_202105_67country_90media_table` A join `dotted-marking-340807.test_20210101_202103031.url_to_country` B on A.SourceCommonName = B.url
and V2Locations is not null
and ActionGeo_CountryCode is not null
group by 
yeardate,
B.country_code,
report_code

In [ ]:
#获取16年1月到21年5月，67个国家，90%媒体的每个国家按日期的报道数和被报道数
select 
FLOOR(date/1000000) as yeardate,
A.country_code,
substring(V2Locations,instr(V2Locations,'#',1,2)+1,instr(V2Locations,'#',1,3)-instr(V2Locations,'#',1,2)-1) as report_code,
count(*) as report_nums
from 
`dotted-marking-340807.test_20210101_202103031.67_country_code` A 
join `dotted-marking-340807.test_20210101_202103031.url_to_country` C 
on A.country_code = C.country_code
join `dotted-marking-340807.test_20210101_202103031.wangyu_201601_202105` D 
on C.url = D.SourceCommonName
join `dotted-marking-340807.test_20210101_202103031.wangyu_201906_202105_source_table` B 
on B.SourceCommonName = D.SourceCommonName
group by 
yeardate,
A.country_code,
report_code

In [ ]:
#获取11年1月到21年5月，全部国家，avgtone的数据。
select 
date,
C.country_code,
substring(V2Locations,instr(V2Locations,'#',1,2)+1,instr(V2Locations,'#',1,3)-instr(V2Locations,'#',1,2)-1) as report_code,
substring(V2Tone,0,instr(V2Tone,',',1,1)-1) as avgTone
from 
`dotted-marking-340807.test_20210101_202103031.url_to_country` C 
join `gdelt-bq.gdeltv2.gkg` D 
on C.url = D.SourceCommonName
join `dotted-marking-340807.test_20210101_202103031.wangyu_201906_202105_source_table` B 
on B.SourceCommonName = D.SourceCommonName
and D.DATE between 20110100000000 and 20210532000000

In [ ]:
#获取11年1月到21年5月，全部国家，按天报道数据。
select 
date,
C.country_code,
substring(V2Locations,instr(V2Locations,'#',1,2)+1,instr(V2Locations,'#',1,3)-instr(V2Locations,'#',1,2)-1) as report_code,
count(*) as nums
from 
`dotted-marking-340807.test_20210101_202103031.url_to_country` C 
join `gdelt-bq.gdeltv2.gkg` D 
on C.url = D.SourceCommonName
join `dotted-marking-340807.test_20210101_202103031.wangyu_201906_202105_source_table` B 
on B.SourceCommonName = D.SourceCommonName
and D.DATE between 20110100000000 and 20210532000000
group by 
date,
C.country_code,
report_code

In [ ]:
#获取15年1月到21年5月，全部国家，报道国家，和被报道两个国家的包含数据，按天报道数据。
select 
date,
C.country_code,
substring(V2Locations,instr(V2Locations,'#',1,2)+1,instr(V2Locations,'#',1,3)-instr(V2Locations,'#',1,2)-1) as report_code_1,
(case when instr(V2Locations,';',1,1) = 0 then ''
else substring(V2Locations,instr(V2Locations,'#',instr(V2Locations,';',1,1),2)+1,instr(V2Locations,'#',instr(V2Locations,';',1,1),3)-instr(V2Locations,'#',1,2)-1)  end) as report_code_2,
count(*) as nums
from 
`dotted-marking-340807.test_20210101_202103031.url_to_country` C 
join `gdelt-bq.gdeltv2.gkg` D 
on C.url = D.SourceCommonName
join `dotted-marking-340807.test_20210101_202103031.wangyu_201906_202105_source_table` B 
on B.SourceCommonName = D.SourceCommonName
and D.DATE between 20110100000000 and 20210532000000
group by 
date,
C.country_code,
report_code

In [ ]:
#将国家排序重排

In [ ]:
;

(case when instr(V2Locations,';',1,1) = 0 then ''
else substring(V2Locations,instr(V2Locations,'#',instr(V2Locations,';',1,1),2)+1,instr(V2Locations,'#',instr(V2Locations,';',1,1),3)-instr(V2Locations,'#',1,2)-1)  end)

In [ ]:
#提取域名,时间等所需要信息。
select
MonthYear,
(case when Actor1CountryCode is not null then Actor1CountryCode 
when Actor2CountryCode is not null then Actor2CountryCode
when ActionGeo_CountryCode is not null then ActionGeo_CountryCode
else null end) as reportcode,
REPLACE(substring(SOURCEURL,instr(SOURCEURL,'/',1,2)+1,
CASE when INSTR((REPLACE(REPLACE(SOURCEURL,'https://',''),'http://','')),'/')-1 > 0 then INSTR((REPLACE(REPLACE(SOURCEURL,'https://',''),'http://','')),'/')-1
when INSTR((REPLACE(REPLACE(SOURCEURL,'https://',''),'http://','')),'/')-1<0 and INSTR((REPLACE(REPLACE(SOURCEURL,'https://',''),'http://','')),'?')-1<0  THEN LENGTH(SOURCEURL)
when INSTR((REPLACE(REPLACE(SOURCEURL,'https://',''),'http://','')),'/')-1<0 and INSTR((REPLACE(REPLACE(SOURCEURL,'https://',''),'http://','')),'?')-1>0  then INSTR((REPLACE(REPLACE(SOURCEURL,'https://',''),'http://','')),'?')-1
ELSE 0 end),'www.','') as SourceCommonName,
AvgTone,
NumArticles,
from
`gdelt-bq.full.events` 
where MonthYear < 201502

In [ ]:
select
report_code,
C.country
from
(
SELECT
substring((REPLACE(REPLACE(SOURCEURL,'https://',''),'http://','')), 1, INSTR((REPLACE(REPLACE(SOURCEURL,'https://',''),'http://','')),'/')-1) report_code,
FROM
`gdelt-bq.full.events` 
where SOURCEURL is not null)D
join `dotted-marking-340807.test_20210101_202103031.url_to_country` C  on C.url like report_code
limit 100

In [ ]:
#读取时间段的按月某国报道广告数目 1
select 
FLOOR(date/100000000) as monthdate,
A.country_code,
count(*) as numreporte
from 
`dotted-marking-340807.test_20210101_202103031.wangyu_202101_202105_report_nums` A
join `dotted-marking-340807.test_20210101_202103031.APEC_country` B on A.country_code = B.country_code
where report_code is not null
group by monthdate,
A.country_code
order by
monthdate,
A.country_code
#读取时间段的按月某国被报道广告数目 2
select 
FLOOR(date/100000000) as monthdate,
report_code,
count(*) as numreporte
from 
`dotted-marking-340807.test_20210101_202103031.wangyu_202101_202105_report_nums` A
join `dotted-marking-340807.test_20210101_202103031.APEC_country` B on A.report_code = B.country_code
where report_code is not null
group by monthdate,
report_code
order by
monthdate,
report_code 
#读取时间段的按月报道广告总数目 3 
select 
FLOOR(date/100000000) as monthdate,
count(*) as numreporte
from 
`dotted-marking-340807.test_20210101_202103031.wangyu_202101_202105_report_nums` A
where report_code is not null
group by monthdate
order by monthdate
#读取时间段内按月报告本国的数目 4
select 
FLOOR(date/100000000) as monthdate,
report_code,
count(*) as numreported
from 
`dotted-marking-340807.test_20210101_202103031.wangyu_202101_202105_report_nums` A
join `dotted-marking-340807.test_20210101_202103031.APEC_country` B on A.report_code = B.country_code
where  A.report_code = A.country_code
and report_code is not null
group by monthdate,
report_code
order by
monthdate,
report_code

In [ ]:
#获取20年的国家之间按月报道数据
select
FLOOR(date/100000000) as monthdate,
A.country_code,
report_code,
sum(f0_) as report_nums
from 
`dotted-marking-340807.test_20210101_202103031.wangyu_202101_202105_report_nums` A
join `dotted-marking-340807.test_20210101_202103031.APEC_country` B on A.country_code = B.country_code
group by
 monthdate,
A.country_code,
report_code

In [ ]:
#按月获取每个国家一个月平均tone，和报道总数
select 
FLOOR(date/100000000) as monthdate,
report_code,
avg(cast(avgTone as DECIMAL)) as avgTone,
count(*) as numreport 
from 
`dotted-marking-340807.test_20210101_202103031.wangyu_201101_202105_avgtone` A
join `dotted-marking-340807.test_20210101_202103031.APEC_country` B on A.report_code = B.country_code
where A.country_code <> A.report_code
and report_code is not null
group by monthdate,
report_code
order by
monthdate,
report_code

In [ ]:
#查询20年报道国家的数据
select
monthdate,
A.en_name,
B.en_name,
report_nums
from
(
select
FLOOR(date/100000000) as monthdate,
en_name,
report_code,
sum(f0_) as report_nums
from 
`dotted-marking-340807.test_20210101_202103031.wangyu_202101_202105_report_nums` A
join `dotted-marking-340807.test_20210101_202103031.APEC_country` B on A.country_code = B.country_code
group by
monthdate,
en_name,
report_code) A join `dotted-marking-340807.test_20210101_202103031.APEC_country` B on A.report_code = B.country_code
where monthdate >= 202001 
and   monthdate <= 202012 
order by
monthdate,
A.en_name,
B.en_name

In [ ]:
#获取11年1月到15年1月，全部国家，按天报道数据。
select 
date,
C.country_code,
substring(V2Locations,instr(V2Locations,'#',1,2)+1,instr(V2Locations,'#',1,3)-instr(V2Locations,'#',1,2)-1) as report_code,
count(*)
from 
`dotted-marking-340807.test_20210101_202103031.url_to_country` C 
join `gdelt-bq.full.events` D 
on C.url = D.SourceCommonName
join `dotted-marking-340807.test_20210101_202103031.wangyu_201906_202105_source_table` B 
on B.SourceCommonName = D.SourceCommonName
and D.DATE between 20110100000000 and 20210532000000
group by 
date,
C.country_code,
report_code

In [1]:
 select 
*
from
(
    select
    source_common_name,
    count(*) as a
    from gkg
    where date >= 20210101000000
      and date <  20220101000000
    group by source_common_name
    having a >4000
    and a <
)
order by a desc

'\nselect \n*\nfrom\n    (\n    select\n     source_common_name,\n      count(*) as a\n    from gkg\n    where date >= 20220808000000\n    and date <    20220810040000\n    group by source_common_name\n    having a >100\n    )\n   order by a desc\n\n'

In [ ]:
#查询每一天每个中国报道国家最多的前十个国家的报道数目。
SELECT
yeardate as monthdate,
country_code,
report_code,
sum(report_nums) report_nums
FROM `dotted-marking-340807.test_20210101_202103031.wangyu_2022_country_report_nums` A
where country_code = 'CH'
and (
  select count(1)
  from `dotted-marking-340807.test_20210101_202103031.wangyu_2022_country_report_nums` B
  WHERE A.yeardate = B.yeardate
  and A.country_code = B.country_code
  and A.report_nums <= B.report_nums
)<= 10
and yeardate >= 20220801  
group by 
monthdate,
country_code,
report_code
having report_nums >=50
order by 
monthdate,
report_nums desc

In [ ]:
POST _sql?format=txt
{
  "fetch_size": 5000,
  "query": 
   """
     select 
*
from
(
    select
    date/1000000 as day,
    count(*) as a
    from gkg
    where date >= 20210101000000
      and date <  20210104000000
    group by day
)
order by day
   """
}

In [ ]:
POST _sql?format=txt
{
  "fetch_size": 5000,
  "query": 
   """
     select 
*
from
(
    select
    substring_index(v2_locations,'#',2)
    from gkg
    limit 10
)

   """
}

In [ ]:
PUT /index_test_gkg
{
  "mappings": {
    "gkg": {
      "properties": {
        "all_names": {
          "type": "text"
        },
        "amounts": {
          "type": "text"
        },
        "counts": {
          "type": "text"
        },
        "date": {
          "type": "long",
          "fields": {
            "kw": {
              "type": "keyword"
            }
          }
        },
        "dates": {
          "type": "text"
        },
        "document_identifier": {
          "type": "text"
        },
        "extras": {
          "type": "text"
        },
        "gcam": {
          "type": "text"
        },
        "gkg_record_id": {
          "type": "keyword"
        },
        "locations": {
          "type": "text"
        },
        "organizations": {
          "type": "text"
        },
        "persons": {
          "type": "text"
        },
        "quotations": {
          "type": "text"
        },
        "related_images": {
          "type": "text"
        },
        "sharing_image": {
          "type": "text"
        },
        "social_image_embeds": {
          "type": "text"
        },
        "social_video_embeds": {
          "type": "text"
        },
        "source_collection_identifier": {
          "type": "long",
          "fields": {
            "kw": {
              "type": "keyword"
            }
          }
        },
        "source_common_name": {
          "type": "keyword"
        },
        "themes": {
          "type": "text"
        },
        "translation_info": {
          "type": "text"
        },
        "v2_counts": {
          "type": "text"
        },
        "v2_locations": {
          "type": "text"
        },
        "v2_organizations": {
          "type": "text"
        },
        "v2_persons": {
          "type": "text"
        },
        "v2_themes": {
          "type": "text"
        },
        "v2_tone": {
          "type": "text"
        }
      }
    }
  }
}

In [ ]:
PUT /index_test_gkg
{
"settings": {
                "number_of_shards": 128,
                "number_of_replicas": 0,
                "refresh_interval": -1
            },
            "mappings": {
                "gkg": {
                    "properties": {
                        "gkg_record_id": {
                            "type": "keyword",
                        },
                        "date": {
                            "type": "long",
                            "fields": {"kw": {"type": "keyword" }}
                        },
                        "source_collection_identifier": {
                            "type": "long",
                            "fields": {"kw": {"type": "keyword" }}
                        },
                        "source_common_name": {
                            "type": "keyword",
                        },
                        "document_identifier": {
                            "type": "text"
                        },
                        "counts": {
                            "type": "text"
                        },
                        "v2_counts": {
                            "type": "text"
                        },
                        "themes": {
                            "type": "text"
                        },
                        "v2_themes": {
                            "type": "text"
                        },
                        "locations": {
                            "type": "text"
                        },
                        "v2_locations": {
                            "type": "text"
                        },
                        "persons": {
                            "type": "text"
                        },
                        "v2_persons": {
                            "type": "text"
                        },
                        "organizations": {
                            "type": "text"
                        },
                        "v2_organizations": {
                            "type": "text"
                        },
                        "v2_tone": {
                            "type": "text"
                        },
                        "dates": {
                            "type": "text"
                        },
                        "gcam": {
                            "type": "text"
                        },
                        "sharing_image": {
                            "type": "text"
                        },
                        "related_images": {
                            "type": "text"
                        },
                        "social_image_embeds": {
                            "type": "text"
                        },
                        "social_video_embeds": {
                            "type": "text"
                        },
                        "quotations": {
                            "type": "text"
                        },
                        "all_names": {
                            "type": "text"
                        },
                        "amounts": {
                            "type": "text"
                        },
                        "translation_info": {
                            "type": "text"
                        },
                        "extras": {
                            "type": "text"
                        },
                    }
                }
            }
}

In [ ]:
select
year,
source_common_name,
action_geo_full_name
from 
\"myindex*\"
where A.document_identifier = B.source_url
and date >= 20210101000000
and date <  20220101000000
and year = 2021

In [9]:
POST _search?format=txt
{
  "query": {
 "bool": {
    "must":[
        {"range": {
            "date_added": {
                "gte": 20200101200000,
                "lte": 20200101240000
            }
        }},
        {"range": {
            "date": {
                "gte": 20200101200000,
                "lte": 20200101240000
            }
        }}]
}
}
  }